// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Layout: typeof import('./components/Layout.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    PublicButton: typeof import('./components/Public/Button.vue')['default']
    PublicImageMap: typeof import('./components/Public/ImageMap.vue')['default']
    PublicMenuButton: typeof import('./components/Public/MenuButton.vue')['default']
    PublicNavbar: typeof import('./components/Public/Navbar.vue')['default']
    PublicNavigationLink: typeof import('./components/Public/NavigationLink.vue')['default']
    PublicProject: typeof import('./components/Public/Project.vue')['default']
    PublicSplashSection: typeof import('./components/Public/SplashSection.vue')['default']
    PublicUserCard: typeof import('./components/Public/UserCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
